const FETCH_PLAYLIST = 'FETCH_PLAYLIST';
const ADD_PLAYLIST = 'ADD_PLAYLIST';
const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
const NEXT_PLAYLIST = 'NEXT_PLAYLIST';
const INITIAL_STATE = [];

export { FETCH_PLAYLIST, ADD_PLAYLIST, DELETE_PLAYLIST, NEXT_PLAYLIST, INITIAL_STATE };
